sudo: required
language: generic

services:
    - docker

before_install:
    - docker build -t khanhnhqdev/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true khanhnhqdev/docker-react npm run test